[tool.poetry]
name = "rabbitmq-sandbox"
version = "0.1.0"
description = ""
authors = ["tayutaedomo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
