version: '3.9'

services:
  rabbitmq:
    container_name: "rabbitmq"
    hostname: ${RABBITMQ_HOSTNAME}
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Admin UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      TZ: "Asia/Tokyo"
