name: RabbitMQ CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Start RabbitMQ with Docker Compose
      run: docker-compose -f docker/docker-compose.yml up -d

    - name: Run tests
      run: poetry run pytest

    - name: Shutdown RabbitMQ
      run: docker-compose -f docker/docker-compose.yml down
