name: RabbitMQ CI

on:
  push:
    branches: [ main ]

env:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_HOST: localhost

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Start RabbitMQ with Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for RabbitMQ to become ready
      run: |
        echo "Waiting for RabbitMQ to become ready..."
        until $(curl --output /dev/null --silent --head --fail http://localhost:15672); do
          printf '.'
          sleep 3
        done
        echo "RabbitMQ is up and running!"

    - name: Run tests
      run: poetry run pytest

    - name: Shutdown RabbitMQ
      run: docker-compose -f docker-compose.yml down
